In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [ ]:
!kaggle datasets download -d arpitjain007/dog-vs-cat-fastai

dog-vs-cat-fastai.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
import zipfile
zip_ref = zipfile.ZipFile('/content/dog-vs-cat-fastai.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

In [ ]:
import cv2
import os
import random
import numpy as np
import matplotlib.pyplot as plt

from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten

In [ ]:
dir = "/content/dogscats/train"
categories = ['cats',"dogs"]

In [ ]:
for i in categories:
  folder = os.path.join(dir,i)
  print(folder)

/content/dogscats/train/cats
/content/dogscats/train/dogs


In [ ]:
# for i in categories:
#   folder = os.path.join(dir,i)
#   for img in os.listdir(folder):
#     img_path = os.path.join(folder,img)
#     print(img_path)
#     break

In [ ]:
# for i in categories:
#   folder = os.path.join(dir,i)
#   for img in os.listdir(folder):
#     img_path = os.path.join(folder,img)
#     img_arr = cv2.imread(img_path)
#     plt.imshow(img_arr)
#     break

In [ ]:
# for i in categories:
#   folder = os.path.join(dir,i)
#   for img in os.listdir(folder):
#     img_path = os.path.join(folder,img)
#     img_arr = cv2.imread(img_path)
#     img_arr =cv2.resize(img_arr,(100,100))
#     plt.imshow(img_arr)
#     break

In [ ]:
data = []
for i in categories:
  folder = os.path.join(dir,i)
  label = categories.index(i)
  for img in os.listdir(folder):
    img_path = os.path.join(folder,img)
    img_arr = cv2.imread(img_path)
    img_arr =cv2.resize(img_arr,(100,100))
    data.append([img_arr,label])

In [ ]:
len(data)

23000

In [ ]:
random.shuffle(data)

In [ ]:
data[0]

[array([[[ 44,  52,  42],
         [  3,   9,   2],
         [  5,  12,   4],
         ...,
         [ 28,  40,  44],
         [ 59,  71,  75],
         [ 32,  44,  48]],
 
        [[ 40,  49,  39],
         [ 11,  19,   9],
         [ 14,  21,  11],
         ...,
         [ 34,  46,  50],
         [ 73,  85,  89],
         [ 42,  54,  58]],
 
        [[ 46,  54,  44],
         [ 34,  43,  33],
         [ 58,  65,  56],
         ...,
         [  6,  16,  20],
         [  4,  15,  20],
         [  6,  19,  22]],
 
        ...,
 
        [[ 84,  78,  79],
         [ 78,  75,  77],
         [ 85,  84,  88],
         ...,
         [211, 210, 206],
         [219, 217, 217],
         [196, 194, 193]],
 
        [[ 85,  73,  85],
         [ 85,  70,  89],
         [107,  91, 117],
         ...,
         [146, 140, 141],
         [140, 129, 143],
         [123, 113, 127]],
 
        [[113,  91, 130],
         [109,  86, 131],
         [122,  96, 148],
         ...,
         [111, 102, 111],
  

In [ ]:
X = []
y = []

In [ ]:
for features,label in data:
  X.append(features)
  y.append(label)

In [ ]:
X = np.array(X)
y = np.array(y)

In [ ]:
len(X),len(y)

(23000, 23000)

In [ ]:
X[0:2]

array([[[[ 44,  52,  42],
         [  3,   9,   2],
         [  5,  12,   4],
         ...,
         [ 28,  40,  44],
         [ 59,  71,  75],
         [ 32,  44,  48]],

        [[ 40,  49,  39],
         [ 11,  19,   9],
         [ 14,  21,  11],
         ...,
         [ 34,  46,  50],
         [ 73,  85,  89],
         [ 42,  54,  58]],

        [[ 46,  54,  44],
         [ 34,  43,  33],
         [ 58,  65,  56],
         ...,
         [  6,  16,  20],
         [  4,  15,  20],
         [  6,  19,  22]],

        ...,

        [[ 84,  78,  79],
         [ 78,  75,  77],
         [ 85,  84,  88],
         ...,
         [211, 210, 206],
         [219, 217, 217],
         [196, 194, 193]],

        [[ 85,  73,  85],
         [ 85,  70,  89],
         [107,  91, 117],
         ...,
         [146, 140, 141],
         [140, 129, 143],
         [123, 113, 127]],

        [[113,  91, 130],
         [109,  86, 131],
         [122,  96, 148],
         ...,
         [111, 102, 111],
        

In [ ]:
y[0:2]

array([0, 1])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
X_train = X_train/255
X_test = X_test/255

In [ ]:
X_train.shape,X_test.shape

((18400, 100, 100, 3), (4600, 100, 100, 3))

In [ ]:
model = Sequential()

model.add(Conv2D(8,kernel_size=(3,3),activation="relu",input_shape=(100,100,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(32,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

In [ ]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [ ]:
model.fit(X_train,y_train,epochs=5,validation_split=0.2)

Epoch 1/5
460/460 [==============================] - 15s 11ms/step - loss: 0.6431 - accuracy: 0.6395 - val_loss: 0.5806 - val_accuracy: 0.6924
Epoch 2/5
460/460 [==============================] - 4s 8ms/step - loss: 0.5590 - accuracy: 0.7121 - val_loss: 0.5497 - val_accuracy: 0.7179
Epoch 3/5
460/460 [==============================] - 3s 7ms/step - loss: 0.5038 - accuracy: 0.7503 - val_loss: 0.5302 - val_accuracy: 0.7337
Epoch 4/5
460/460 [==============================] - 3s 7ms/step - loss: 0.4621 - accuracy: 0.7756 - val_loss: 0.5370 - val_accuracy: 0.7285
Epoch 5/5
460/460 [==============================] - 3s 7ms/step - loss: 0.4132 - accuracy: 0.8055 - val_loss: 0.5602 - val_accuracy: 0.7196


#### Cat

In [ ]:
input_img = cv2.imread("/content/cat.jpg")

In [ ]:
input_img.shape

(315, 474, 3)

In [ ]:
input1 = cv2.resize(input_img,(100,100))

In [ ]:
input1 = input1.reshape(1,100,100,3)

In [ ]:
model.predict(input1)

1/1 [==============================] - 0s 223ms/step


array([[0.]], dtype=float32)

#### Dog

In [ ]:
input_img = cv2.imread("/content/dog.jpg")

In [ ]:
input_img.shape

(1200, 1600, 3)

In [ ]:
input2 = cv2.resize(input_img,(100,100))

In [ ]:
input2 = input2.reshape(1,100,100,3)

In [ ]:
model.predict(input2)

1/1 [==============================] - 0s 94ms/step


array([[1.]], dtype=float32)